# Generated by Django 3.1.1 on 2020-09-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Check this outttt', max_length=300),
            preserve_default=False,
        ),
    ]
