# Generated by Django 3.1.1 on 2020-09-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
