# Generated by Django 3.1.1 on 2020-10-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20201001_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='problem',
            field=models.TextField(default='enter problem'),
            preserve_default=False,
        ),
    ]
